In [36]:
# import numpy
# create array x

import numpy as np

t = array[(2,3,4),(4,5,6),(7,8,9)]
print(t)

w = np.arange(42).reshape(6,7)
print(w)

x = np.arange(24).reshape(4,6)
print(x)

y = np.arange(12).reshape(3,4)
print(y)

z = np.arange(48).reshape(8,6)
print(z)


'''
in_x = [4,5,6,7,8,9]
in_y = [1,2,3]
x = []

def array_er():
    for w in in_x:
        for v in in_y:
            x.append(w/v)
        
    return(x)
'''



NameError: name 'array' is not defined

In [15]:
# print the shape of x

print(x.shape)

(4, 6)


In [16]:
# create a two dimensional array
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [17]:
# print shape of 2d array
print(y.shape)

(5, 7)


In [22]:
# reshape the array to 2 x 6
y.shape = (2,6)
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [24]:
# reshape the array to 1 x 12

y.shape = (1,12)
print(y)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [30]:
# transpose the array

np.transpose(y)
print(y)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [31]:
# indexing method 1
z[4,3]

27

In [32]:
# indexing method 2
z[2:4,0:3]

array([[12, 13, 14],
       [18, 19, 20]])

In [45]:
# indexing method 3
k = z>10
k.reshape(12,4)
print(z[k])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47]


In [43]:
# indexing method 4

h = w.reshape(3,7,2)
print(w)
print(h[:,0,:])
print(h[0,:,:])
print(h[:,:,0])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[ 0  1]
 [14 15]
 [28 29]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[[ 0  2  4  6  8 10 12]
 [14 16 18 20 22 24 26]
 [28 30 32 34 36 38 40]]


In [11]:
# indexing method 5

In [10]:
# indexing method 6