In [15]:
import numpy as np
a = np.array([1, 2.0, 3, 4, 5, 6])
b = np.array([5, 4, 3, 2.0, 1])

In [11]:
a


array([1, 2, 3, 4, 5])

In [16]:
reshaped_b = b.reshape(1,-1) #this makes it a one dimensional matrix
print(reshaped_b)

[[ 5.  4.  3.  2.  1.]]


In [17]:
reshaped_a = a.reshape(3,2)
print(reshaped_a)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [16]:
np.add(a, b)

array([6, 6, 6, 6, 6])

In [17]:
np.subtract(a, b)

array([-4, -2,  0,  2,  4])

In [14]:
np.dot(a, b)

35

In [20]:
c = np.array([6, 5, 4, 3, 2, 1])
d = np.array([6, 5, 4, 3, 2, 1])

matrix_c = c.reshape(2,3)
vector_d = d.reshape(1,-1)

tc = type(matrix_c)
td = type(vector_d)

#print(tc)
#print(td)
print(c, type(c), c.ndim, c.shape)
print(d, type(d), d.ndim, d.shape)
print(matrix_c, tc, matrix_c.ndim, matrix_c.shape)
print(vector_d, td, vector_d.ndim, vector_d.shape)



(array([6, 5, 4, 3, 2, 1]), <type 'numpy.ndarray'>, 1, (6,))
(array([6, 5, 4, 3, 2, 1]), <type 'numpy.ndarray'>, 1, (6,))
(array([[6, 5, 4],
       [3, 2, 1]]), <type 'numpy.ndarray'>, 2, (2, 3))
(array([[6, 5, 4, 3, 2, 1]]), <type 'numpy.ndarray'>, 2, (1, 6))


In [21]:
print(c.dtype, matrix_c.dtype, d.dtype, vector_d.dtype)

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))


In [22]:
np.dot(c,d)

91

In [23]:
np.dot(d,c)

91

In [24]:
s1 = np.array(['a','b'])
s2 = np.array([2,3])


In [25]:
np.add(s1,s2)

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S21') dtype('S21') dtype('S21')

In [26]:
np.dot(s1,s2)

ValueError: data type must provide an itemsize

In [28]:
s1*s2

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('S21') dtype('S21') dtype('S21')

In [29]:
c*d

array([36, 25, 16,  9,  4,  1])

In [47]:
list_one = [1,3,5,7,9]
list_two = [2,4,6,8,10]

#indexing method attempt

final_array = []
for n in range(len(list_one)):
    final_array.append(list_one[n]*list_two[n])

sum(final_array)
        

190

In [48]:
list_one = [1,3,5,7,9]
list_two = [2,4,6,8,10]

#enumerate method attempt

final_array = []
one = enumerate(list_one)
two = enumerate(list_two)
for i in (range(len(list_one))
for i,j in one:
    for x,y in two:
        if i == x:
            final_array.append(j*y)
    
print(final_array)        
sum(final_array)
        

[2]


2

In [59]:
%%timeit
last_array = []
list_one = [1,3,5,7,9]
list_two = [2,4,6,8,10]

combined_list = zip(list_one, list_two)
for a,b in combined_list:
    last_array.append(a*b)
        
return(sum(last_array))
        

1 loops, best of 3: 3min 10s per loop


In [63]:
%%timeit
#most simple
def dot_proder(list_one, list_two):
    if len(list_one) == len(list_two):
        return sum([x*y for x,y in zip(list_one, list_two)])
    
        
dot_proder(list_one, list_two)

The slowest run took 5.65 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.43 µs per loop


In [50]:
lista = [2,3,4]
listb = [4,5,6,7]
#the 7 in listb gets erased if you zip them because lists aren't same length
zip(lista, listb)

[(2, 4), (3, 5), (4, 6)]